version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo "Installing dependencies..."
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -version

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Cleaning previous builds..."

  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Running Maven clean package..."
      - mvn clean package -DskipTests=false
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Verifying JAR file creation..."
      - ls -la target/
      - echo "JAR file size:"
      - du -h target/lambda-service.jar
      - echo "Build completed successfully"

artifacts:
  files:
    - target/lambda-service.jar
    - aws-lambda-config.json
  name: lambda-service-artifacts
  base-directory: '.'

cache:
  paths:
    - '/root/.m2/**/*'

reports:
  surefire-reports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    file-format: 'JUNITXML'

environment_variables:
  plaintext:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
